//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowDance.Examples.TripBookingSaga.CarService.HotelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelService.IHotel")]
    public interface IHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/BookHotel", ReplyAction="http://tempuri.org/IHotel/BookHotelResponse")]
        void BookHotel(string passportNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/BookHotel", ReplyAction="http://tempuri.org/IHotel/BookHotelResponse")]
        System.Threading.Tasks.Task BookHotelAsync(string passportNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChannel : FlowDance.Examples.TripBookingSaga.CarService.HotelService.IHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelClient : System.ServiceModel.ClientBase<FlowDance.Examples.TripBookingSaga.CarService.HotelService.IHotel>, FlowDance.Examples.TripBookingSaga.CarService.HotelService.IHotel {
        
        public HotelClient() {
        }
        
        public HotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BookHotel(string passportNumber) {
            base.Channel.BookHotel(passportNumber);
        }
        
        public System.Threading.Tasks.Task BookHotelAsync(string passportNumber) {
            return base.Channel.BookHotelAsync(passportNumber);
        }
    }
}
